version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: Greeting
          command: ./enerestar

      - run:
          name: Print the Current Time
          command: date

      - run:
          name: pre-dependencies
          command: apt-get -y update && apt-get -y install git python curl

      - run:
          name: release
          command: ./release.sh
